package com.hibernate;
// Generated 11-07-2018 02:03:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Valoracion generated by hbm2java
 */
public class Valoracion  implements java.io.Serializable {


     private int idValoracion;
     private String tipoValoracion;
     private Date fecha;

    public Valoracion() {
    }

	
    public Valoracion(int idValoracion) {
        this.idValoracion = idValoracion;
    }
    public Valoracion(int idValoracion, String tipoValoracion, Date fecha) {
       this.idValoracion = idValoracion;
       this.tipoValoracion = tipoValoracion;
       this.fecha = fecha;
    }
   
    public int getIdValoracion() {
        return this.idValoracion;
    }
    
    public void setIdValoracion(int idValoracion) {
        this.idValoracion = idValoracion;
    }
    public String getTipoValoracion() {
        return this.tipoValoracion;
    }
    
    public void setTipoValoracion(String tipoValoracion) {
        this.tipoValoracion = tipoValoracion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


